#!/bin/bash
#
# pbrisbin 2011
#
# http://wiki.archlinux.org/index.php/Udev
#
###

message() { echo 'usage: automount [ on | off ]' >&2; exit 1; }

write_file() {
  local   alph=({a..z})
  local in_use=(/dev/sd?)
  local    nxt="${alph[${#in_use[*]}]}"

  [[ -z "$nxt" ]] && return 1

  cat > "$file" << EOF
KERNEL!="sd[$nxt-z][0-9]", GOTO="media_by_label_auto_mount_end"

# Import FS infos
IMPORT{program}="/sbin/blkid -o udev -p %N"

# Get a label if present, otherwise specify one
ENV{ID_FS_LABEL}!="", ENV{dir_name}="%E{ID_FS_LABEL}"
ENV{ID_FS_LABEL}=="", ENV{dir_name}="usbhd-%k"

# Global mount options
ACTION=="add", ENV{mount_options}="relatime,users"
# Filesystem-specific mount options
ACTION=="add", ENV{ID_FS_TYPE}=="vfat|ntfs", ENV{mount_options}="\$env{mount_options},utf8,gid=100,umask=002"

# Mount the device
ACTION=="add", RUN+="/bin/mkdir -p /media/%E{dir_name}", RUN+="/bin/mount -o \$env{mount_options} /dev/%k /media/%E{dir_name}"

# Clean up after removal
ACTION=="remove", ENV{dir_name}!="", RUN+="/bin/umount -l /media/%E{dir_name}", RUN+="/bin/rmdir /media/%E{dir_name}"

# Exit
LABEL="media_by_label_auto_mount_end"
EOF
}

file='/etc/udev/rules.d/11-media-by-label-auto-mount.rules'

case "$1" in
  on)  write_file    ;;
  off) rm -f "$file" ;;
  *)   message       ;;
esac
