#!/bin/bash
#
# pbrisbin 2010
#
# rewritten based on ideas from falconindy's SquashFu:
#       http://github.com/falconindy/SquashFu
#
###

message()  { echo 'usage: backup [ -d | -m | --media ]'; exit 1; }
errorout() { echo "error: $*" >&2; exit 1; }

# normal backup settings
backup_daily='/mnt/backup/daily'
backup_monthly='/mnt/backup/monthly'

includes=(/srv/http /home/patrick /etc /usr /var /boot)
excludes=(Downloads lost+found)

# my large media collection is handled specially
backup_media='/mnt/backup2'
media_includes=(/mnt/data1/Rips /mnt/data2/Movies /mnt/data2/TV_shows)
media_excludes=(converted)

if [[ "$1" = '--media' ]]; then
  # do a media compression and exit
  echo "compressing media to $backup_media/media.tbz2"
  tar cpjf "$backup_media/media.tbz2" ${media_excludes[@]/#/--exclude } "${media_includes[@]}"
  exit $?
fi

case "$1" in
  -d|--daily)   backup_dir="$backup_daily"   ;;
  -m|--monthly) backup_dir="$backup_monthly" ;;
  *)            message                      ;;
esac

# default
backup_dir="${backup_dir:-$backup_daily}"

# initial checks
[[ $(id -u) -eq 0         ]] || errorout 'only root can do that...'
[[ -f "$backup_dir/.lock" ]] || errorout "$backup_dir/.lock not found, is it mounted?"

echo "syncing directories to $backup_dir/"
rsync -a -l --delete --delete-excluded "${includes[@]}" ${excludes[@]/#/--exclude } "$backup_dir/"

echo 'generating package lists...'
pacman -Qqe | grep -Fvx "$(pacman -Qqm)" > "$backup_dir/paclog" || errorout 'failed creating paclisting'
pacman -Qqm > "$backup_dir/aurlog"                              || errorout 'failed creating aur listing'

echo 'done'
