#!/bin/bash -e
#
# pbrisbin 2011
#
# takes ideas from falconindy's SquashFu:
#       http://github.com/falconindy/SquashFu
#
###

check_root() { # {{{
  if [[ $(id -u) -ne 0 ]]; then
    echo 'you must be root' >&2
    exit 1
  fi
}
# }}}

check_lock() { # {{{
  if [[ ! -f "$DIR/.lock" ]]; then
    echo "${DIR:-unknown}/.lock not found" >&2
    exit 2
  fi
}
# }}}

check_exec() { # {{{
  if ! type -p "${EXEC%% *}"; then
    echo "Function undefined for backup type" >&2
    exit 3
  fi
}
# }}}

rsynccmd() { # {{{
  rsync -a --delete --delete-excluded \
    "$@" "${INCLUDES[@]}" ${EXCLUDES[@]/#/--exclude } "$DIR/"
}
# }}}

rsync_and_pkg_list() { # {{{
  rsynccmd "$@"
  pacman -Qqe | grep -Fvx "$(pacman -Qqm)" > "$DIR/paclog"
  pacman -Qqm > "$DIR/aurlog"
}
# }}}

rsync_and_pkg_list_remote() { # {{{
  local host="$1"; shift

  if ping -c 1 $host &>/dev/null; then 
    rsynccmd -e ssh "$@"
    ssh root@$host 'pacman -Qqe | grep -Fxv "$(pacman -Qqm)"' > "$DIR/paclog"
    ssh root@$host 'pacman -Qqm' > "$DIR/aurlog"
  fi
}
# }}}

setup_backup_for() { # {{{
  local name="$1" var

  DIR=
  EXEC=

  # the directory to backup to
  var="${name}_destination"
  DIR="${!var}"

  # an array of files/directories to include
  var="${name}_includes[@]"
  INCLUDES=( "${!var}" )

  # an array of files/directories to exclude
  var="${name}_excludes[@]"
  EXCLUDES=( "${!var}" )

  # the function to call the execute the actual backup after checking
  # that the destination is available. the function is passed any
  # additional command lines args directly
  var="${name}_execute"
  EXEC="${!var}"

  check_root
  check_lock
  check_exec
}
# }}}

# A normal, file and pkg list backup
daily_destination='/mnt/backup/daily'
daily_includes=( /srv/http /home/patrick /etc /usr /var /boot )
daily_excludes=( Documents/ripping Downloads lost+found )
daily_execute=rsync_and_pkg_list

# The same except to a different destination
monthly_destination='/mnt/backup/monthly'
monthly_includes=( "${daily_includes[@]}" )
monthly_excludes=( "${daily_excludes[@]}" )
monthly_execute="$daily_execute"

# Media just needs rsync so it can use it directly
media_destination='/mnt/backup2'
media_includes=( /mnt/media/Music /mnt/media/Rips /mnt/media/Movies /mnt/media/TV_shows )
media_excludes=()
media_execute=rsynccmd

# An example of backup-over-ssh
htpc_destination='/mnt/backup/htpc/'
htpc_includes=( root@htpc:/etc root@htpc:/home/xbmc )
htpc_excludes=()
htpc_execute='rsync_and_pkg_list_remote htpc'

declare -a INCLUDES
declare -a EXCLUDES

setup_backup_for "$1"
shift; $EXEC "$@"
