#!/bin/bash
#
# pbrisbin 2009, 2010, 2011
#
###

message() { echo 'usage: bookmark [ --add <category> <url> ]'; exit 1; }

find_title() { curl --silent "$1" | sed -e '/.*<title>\(.*\)<\/title>.*/!d;s//\1/g'; }

insert_bookmark() {
  [[ $# -ne 2 ]] && message

  local title entry
  local dir="$(find "$bookmarks" -type d -wholename "$bookmarks/$1")" 
  local url="$2"

  [[ -d "$dir"           ]] || mkdir -p "$dir" 
  [[ -f "$dir/bookmarks" ]] || touch "$dir/bookmarks"

  title="$(find_title "$url")"
  entry="$url|$title"

  if ! grep -Fqx "$entry" "$dir/bookmarks"; then
    echo "$entry" >> "$dir/bookmarks" && echo "added: ${dir/$bookmarks/}/$title"
  fi

  exit
}

add_bookmarks() {
  local LC_ALL='C' path dir url title

  for path in $(find "$bookmarks" -type f -name bookmarks | sort); do
    dir="$(dirname "$path")"

    echo "<h3>${dir/$bookmarks/}</h3>"
    
    while IFS='|' read -r url title; do
      echo "<p><a href=\"$url\" title=\"${title}\">${title:-${url/http:\/\//}}</a></p>"
    done < "$path"
  done
}

write_css() {
  cat > "$css_file" << EOF
body {
  width:            710px;
  margin-left:      auto;
  margin-right:     auto;
  color:            #bbbbbb;
  background-color: #303030;
  font:             13px/1.231 sans-serif;
  font-family:      helvetica, "Georgia Sans", verdana, sans-serif
  font-weight:      normal;
}

h1, h3 { color: #ffffff; font-weight: normal; }
h3     { margin-left: -2%; }

a:link, a:visited, a:hover { outline: none; text-decoration: none; }
a:link, a:visited { color: #91bfc2; }
a:hover           { color: #a291c2; }
EOF
}

write_html() {
  cat > "$html_file" << EOF
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bookmarks</title>
    <link type="text/css" rel="stylesheet" href="${css_file##*/}" />
  </head>
  <body>
    <h1 class="title">Bookmarks</h1>
    <hr />
    <!-- begin bookmarks -->

    $(add_bookmarks)

    <!-- end bookmarks -->
  </body>
</html>
EOF
}

open_page() { $BROWSER "file://$html_file"; }

# adjust these
bookmarks="$HOME/.my_bookmarks"
srv_dir='/srv/http/static/fileshare'

# don't touch
html_file="$srv_dir/bookmarks.html"
css_file="$srv_dir/bookmarks.css"

[[ "$1" = '--add' ]] && insert_bookmark "$2" "$3"

write_css
write_html
open_page
