#!/bin/bash
#
# pbrisbin 2009, 2010
#
###

message() { echo 'usage: bookmark [ --add <category> <url> ]'; exit 1; }

find_title() { curl --silent "$1" | sed -e '/.*<title>\(.*\)<\/title>.*/!d;s//\1/g'; }

insert_bookmark() {
  [[ $# -ne 2 ]] && message

  local title entry
  local dir="$(find "$bookmarks" -type d -wholename "$bookmarks/$1")" 
  local url="$2"

  [[ -d "$dir"           ]] || mkdir -p "$dir" 
  [[ -f "$dir/bookmarks" ]] || touch "$dir/bookmarks"

  title="$(find_title "$url")"
  entry="$url|$title"

  if ! grep -Fqx "$entry" "$dir/bookmarks"; then
    echo "$entry" >> "$dir/bookmarks" && echo "added: ${dir/$bookmarks/}/$title"
  fi

  exit
}

create_page() {
  local LC_ALL='C' path dir url title

  echo '<html><head>'             >  "$page"
  echo '<title>Bookmarks</title>' >> "$page"

  if [[ -n "$css_file" ]]; then
    echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"$css_file\" />" >> "$page"
  fi

  echo '</head><body>'                    >> "$page"
  echo '<h1 class="title">Bookmarks</h1>' >> "$page"
  echo '<hr />'                           >> "$page"

  # write each category's section
  for path in $(find "$bookmarks" -type f -name bookmarks | sort); do
    dir="$(dirname "$path")"

    echo "<h3>${dir/$bookmarks/}</h3>" >> "$page"
    
    while IFS='|' read -r url title; do
      echo "<p><a href=\"$url\">${title:-${url/http:\/\//}}</a></p>" >> "$page"
    done < "$path"
  done

  echo '</body></html>' >> "$page"
}

open_page() { $BROWSER "file://$page"; }

bookmarks="$HOME/.my_bookmarks"
page='/srv/http/static/fileshare/bookmarks.html'
css_file='bookmarks.css'

[[ "$1" = '--add' ]] && insert_bookmark "$2" "$3"

create_page
open_page
