#!/bin/bash
#
# pbrisbin 2010
#
# set this as $BROWSER and/or URxvt.urlLauncher in .Xdefaults to quickly
# mess with your default browser without reloading anything
#
###

[[ -n "$DISPLAY" ]] || exit 1

browser='chromium'
$browser "$@" &>/dev/null & exit 0
