#!/bin/bash
#
# pbrisbin 2009, 2010
#
###

message() { 
  cat << EOF
  usage: burn [ -c ] [ -i ] <file> ...
         burn [ -c ] <iso>

    options:
      -c, --cd          burn as cd-r
      -i, --iso         just make an iso

EOF
  exit 1
}

make_iso() {
  local file target img="$dir/image.iso"

  mkdir "$dir/to_burn"

  for file; do
    read -r target < <(readlink -f "$file")
    [[ -e "$target" ]] && ln -s "$target" "$dir/to_burn/"
  done

  mkisofs -o "$img" -f -r -J -l -allow-leading-dots "$dir/to_burn/" || exit $?

  $iso && { cp -v "$img" ./; exit $? }
  
  burn_iso "$img"
}

burn_iso() {
  local img="$1"

  [[ ! -e "$img" ]] && exit 1

  if $ascd; then
    cdrecord -v speed=48 dev=$dev "$iso" || exit $?
  else
    growisofs -dvd-compat -Z $dev="$iso" || exit $?
  fi
}

ascd=false
iso=false

dir='/tmp/burn'
dev='/dev/sr0'

args=()

while [[ -n "$1" ]]; do
  case "$1" in
    -c|--cd)   ascd=true      ;;
    -i|--iso)  iso=true       ;;
    -h|--help) message        ;;
    *)         args+=( "$1" ) ;;
  esac
  shift
done

[[ -d "$dir" ]] && rm -r "$dir"; mkdir "$dir"

# if only one arg and it's *.iso, burn it and exit
[[ "${#args[@]}" -eq 1 ]]        \
  && [[ "${args[0]}" =~ .iso$ ]] \
  && { burn_iso "${args[0]}"; exit $? }

# else, make the iso from the arguments; possibly burn it
make_iso "${args[@]}"

rm -r "$dir"
