#!/bin/bash
#
# pbrisbin 2012
#
###
(( $# )) || { echo 'usage: burn [ -c ] file.iso' >&2; exit 1; }

if [[ $1 =~ -c|--cd ]]; then
  shift; cdrecord -v speed=48 dev=/dev/sr0 "$1"
else
  growisofs -dvd-compat -Z /dev/sr0="$1"
fi
