#!/bin/bash -e
#
# pbrisbin 2011
#
# remove or (re)install all (user) cabalized packages
#
###

message() { 
  cat << EOF
usage: cabalupdate [ --remove | --install ]
  options:

    --remove    remove all cabalized packages only
    --install   install all cabalized packages only

EOF
  exit 1
}

remove_cabal_packages() {
  rm -r "$HOME/.cabal/packages"/*/*
  rm -r "$HOME/.ghc"
}

reinstall_cabal_packages() {
  cabal update

  # xmonad
  cabal install xmonad xmonad-contrib

  # other cabal packages
  cabal install -fhighlighting pandoc \
                libmpd                \
                hlint                 \
                yeganesh              \
                haddock

  # yesod development
  for repo in hamlet persistent wai yesod; do
    (
      cd ~/Code/haskell/$repo
      git pull
      ./install-all.sh
    )
  done

  # fix/get yesod-dependant packages
  fixyesod
}

[[ "$1" =~ -h|--help ]] && message

[[ "$1" == '--install' ]] || remove_cabal_packages
[[ "$1" == '--remove'  ]] || reinstall_cabal_packages
