#!/bin/bash -e
#
# pbrisbin 2011
#
# remove or (re)install all (user) cabalized packages
#
###

message() { 
  cat << EOF
usage: cabalupdate [ --remove | --install ]
  options:

    --remove    remove all cabalized packages only
    --install   install all cabalized packages only

EOF
  exit 1
}

remove_cabal_packages() {
  rm -r "$HOME/.cabal/packages"/*/*
  rm -r "$HOME/.ghc"
}

reinstall_cabal_packages() {
  cabal update

  # xmonad
  cabal install xmonad xmonad-contrib

  # yesod
  cabal install yesod                 \
                yesod-newsfeed        \
                persistent-sqlite     \
                wai-handler-fastcgi   \
                -fhighlighting pandoc \
                hlint                 \
                yeganesh              \
                haddock
}

[[ "$1" =~ -h|--help ]] && message

[[ "$1" == '--install' ]] || remove_cabal_packages
[[ "$1" == '--remove'  ]] || reinstall_cabal_packages
