#!/bin/bash
#
# pbrisbin 2011
#
# burn an audio cd from a directory of files
#
###

message() { echo 'usage: cda <file> ...'; exit 1; }

[[ -z "$1" ]] || [[ "$1" =~ -h|--help ]] && message

dir='/tmp/cda'
dev='/dev/sr0'

[[ -d "$dir" ]] && rm -r "$dir"; mkdir "$dir"

i=0
for file; do
  dest="$dir/$((i++)).wav"

  [[ "$file" =~ .wav$|.WAV$ ]] && { ln -s "$file" "$dest"; continue; }

  mplayer -vo null -vc null \
    -af lavcresample=44100,channels=2,format=s16le \
    -ao pcm:file="$dest" "$file" || exit $?
done

cdrecord dev=$dev fs=4096k -v -useinfo speed=48 -dao -eject -pad -audio "$dir"/*.wav
