#!/bin/bash
#
# pbrisbin 2009
#
###

errorout() { echo "error: $*" >&2; exit 1; }

update_dns() {
  local file="$HOME/.credentials"

  echo "ip changed: $old -> $new"

  # read user/pass from cred file
  [[ -f "$file" ]] && . "$file" || errorout 'dns not updated, credentials file not found'

  # try to update with zonedit
  wget -q -O - --http-user=$zuser --http-passwd=$zpass "$zurl" &>/dev/null || errorout 'dns not updated, wget failure'

  # store new ip
  echo $new > "$ipfile"
  echo 'dns updated. the change may take up to an hour to be seen.'
}

ipfile="$HOME/.myip"

touch "$ipfile"

read -r old < "$ipfile"
read -r new < <(wget -q -O - 'http://tnx.nl/ip')

[[ "$old" != "$new" ]] && update_dns || exit 0
