#!/bin/bash

(( $UID )) && errorout 'you must be root'

perform_check() {
  cat << EOF
Subject: Rootkit check performed
Date: $(date -u +"%a, %d %h %Y %T +0000")
From: Rootkit Check <admin@pbrisbin.com>
To: pbrisbin@gmail.com

Rootkit check was performed today.

------------------------------------------------------------------------------------------
EOF

  /usr/bin/rkhunter --versioncheck --nocolors
  /usr/bin/rkhunter --update --nocolors
  /usr/bin/rkhunter --cronjob --nocolors --report-warnings-only

  cat << EOF
------------------------------------------------------------------------------------------

Thanks,
Admin

EOF
}

perform_check | /usr/sbin/sendmail -f 'admin@pbrisbin.com' pbrisbin@gmail.com
