#!/bin/bash

cache="$HOME/.cache/dynamic-ip"
touch "$cache"

read -r old < "$cache"
read -r new < <(wget -q -O - 'http://tnx.nl/ip')

if [[ "$old" != "$new" ]]; then
  /usr/sbin/sendmail -f 'admin@pbrisbin.com' pbrisbin@gmail.com << EOF
Subject: Your IP has changed
Date: $(date -u +"%a, %d %h %Y %T +0000")
From: Dynamic IP <admin@pbrisbin.com>
To: pbrisbin@gmail.com

Hey,

You're dynamic IP address seems to have changed.

Old address: $old
New address: $new

Please update accordingly at:

https://account.dyn.com/dns/dyn-standard-dns/pbrisbin.com

Thanks,
Admin

EOF
fi
