#!/bin/bash

(( $UID )) && { echo 'you must be root' >&2; exit 1; }

(

  /usr/bin/rkhunter --versioncheck --nocolors
  /usr/bin/rkhunter --update --nocolors
  /usr/bin/rkhunter --cronjob --nocolors --report-warnings-only

) | sys-email 'Rootkit check performed'
