#!/bin/bash
#
# conky companion to ~/.bin/coverart
#
# note: covers are kept at ~/Music/artist/album/folder.jpg
#
# simply add this to conkyrc:
#
#   imlib_cache_size 0
#
#   TEXT
#   ${execp ~/path/to/this}
#
###

get_nowplaying() {
  local file

  file="$(mpc --format '%file%' | head -n 1)"

  dirname "$file"
}

link_image() {
  local album="$1" last cover link
  
  # get last
  read -r last < "$log"

  # if different, relog/relink
  if [[ "$album" != "$last" ]]; then
    echo "$album" > "$log"

    cover="$mdir/$album/folder.jpg"

    # no cover?
    [[ -f "$cover" ]] && link="$cover" || link="$none"
    
    ln -sf "$link" "$image"
  fi
}

# how to display the image in conky (pixels)
g='250x250' # image geometry
x=0         # x offset
y=0         # y offset

# music directory
mdir="$HOME/Music"

# resource directory
dir="$XDG_CONFIG_HOME/conkycovers"

log="$dir/playing.log"
none="$dir/nocover.jpg"
image="$dir/cover.jpg"

[[ ! -d "$dir" ]] && mkdir -p "$dir"
[[ ! -f "$log" ]] && touch "$log"

link_image "$(get_nowplaying)"

# echo what's to be parsed by conky
echo -n "\${image $image -p $x,$y -s $g}" 
