#!/bin/bash
#
# pbrisbin 2010
#
# fetch and organize albumart for your music collection
#
# images are stored both alongside the media as folder.jpg and copied 
# into a central directory, each image named as artist_album.jpg.
#
###

# strip out (Crap) / Disc X / Volume Y
clean_string() {
  sed -r '
  s/(.*) +\([^\)]*\)/\1/g;
  s/(.*) +\(.*/\1/g;
  s/(.*) +\[?[Dd]is[ck].*/\1/g;
  s/(.*) +\[?[Vv]olume.*/\1/g;
  ' <<< "$*"
}

# make a sane, tag-based filename
fix_filename() {
  sed -r '
  s/.*/\L&/g;
  s/ /_/g;
  s/[^a-z0-9_.-]//g;
  s/$/.jpg/g;
  ' <<< "$*"
}

fetch_cover() {
  local artist="$1" album="$(clean_string "$2")" output="$3" cover_url

  # https://github.com/pbrisbin/albumart
  read -r cover_url < <(albumart.php -a "$artist" -b "$album" 2>/dev/null)
  [[ "$cover_url" =~ ^http:// ]] && wget -O "$output" "$cover_url"
}

read_tags() {
  local file="${1/$mdir\//}"
  unset artist album

  read -r artist < <(mpc list artist any "$file")
  read -r album  < <(mpc list album  any "$file")

  [[ -n "$artist$album" ]]
}

copy_albumart() {
  local filename="$1" artist="$2" album="$3" ofilename
  ofilename="$odir/$(fix_filename "$artist" "$album")"
  [[ ! -f "$ofilename" ]] && cp -v "$filename" "$ofilename"
}

# constants
mdir="$HOME/Music"
odir='/srv/http/static/covers'
cover='folder.jpg'

while read -r directory; do
  unset artist album filename

  filename="$directory/$cover"

  if [[ -f "$filename" ]]; then
    for file in "$directory"/*; do read_tags "$file" && break; done
    [[ -n "$artist$album" ]] && copy_albumart "$filename" "$artist" "$album"
  else
    for file in "$directory"/*; do read_tags "$file" && break; done

    [[ -n "$artist$album" ]] && \
      fetch_cover "$artist" "$album" "$filename" && \
      copy_albumart "$filename" "$artist" "$album"
  fi
done < <(find "$mdir/" -type f -exec dirname {} \; | sort -u)

exit 0
