#!/bin/bash
#
# original script by sen on arch forums
#
# rewritten by pbrisbin 2009, 2010
#
###

message() { echo 'usage: cuesplit <directory>'; exit 1; }

split() {
  case "$1" in
    mp3|ogg) mp3splt -no "@a/@b/@n_@t" -c *.cue *."$1"
             cuetag.sh *.cue *."$1" ;;
    *)       cuebreakpoints *.cue | shnsplit -a track -o flac *."$1"
             cuetag.sh *.cue track*.flac ;;
  esac
}

[ -d "$1" ] && cd "$1" || message

case $(ls -1) in
  *.ape*)  split ape  ;;
  *.flac*) split flac ;;
  *.mp3*)  split mp3  ;;
  *.ogg*)  split ogg  ;;
  *.wv*)   split wv   ;;
  *.wav*)  split wav  ;;
  *)       message    ;;
esac
