#!/bin/bash
#
# pbrisbin 2010
#
# don't run this as root as we rely on user-specific ENV vars and haskell
# modules; sudo is used for the parts that require it
#
###

errorout() { echo "error: $*" >&2; exit 1; }
message()  { echo 'usage: deploy [ --wipe | --post | --force | --test | --help ]'; exit 1; }

compile_site() {
  $post  && touch Posts.hs
  $force && find ./ -type f -name '*.hs' -exec touch {} \;

  if ! $test; then
    echo 'recompiling the application for production...'
    sed -i 's/^-- \(#define PRODUCTION\)$/\1/g' Settings.hs
    ghc --make -o app.cgi fastcgi.hs || errorout 'failed'
    sed -i 's/^\(#define PRODUCTION\)$/-- \1/g' Settings.hs
  else
    echo 'recompiling the application...'
    ghc --make -o app.cgi fastcgi.hs || errorout 'failed'
  fi

  mv_file app.cgi
}

mv_file() {
  local file="$1"

  if [[ -e "$file" ]]; then
    $test && cp='cp -r' || cp='sudo cp -r'
    $cp "$file" "$prodsite/" || errorout "$file: failed to copy"
  else
    echo "omitting $file; does not exist" >&2
  fi
}

prompt() {
  read -p "$* [Y/n]? " a

  case ${a:-y} in
    Y*|y*) return 0 ;;
    *)     return 1 ;;
  esac
}

devsite="$HOME/Code/haskell/devsite"
prodsite='/srv/http'

wipe=false
post=false
force=false
test=false

while [[ -n "$1" ]]; do
  case "$1" in
    '--help')  message    ;;
    '--force') force=true ;;

    # these can't both be true
    '--wipe')  $post || wipe=true ;;
    '--post')  $wipe || post=true ;;

    # a test deployment through lighttpd
    '--test')  wipe=false
               post=false
               test=true
               prodsite="$HOME/http-test"
               [[ -d "$prodsite" ]] && rm -rf "$prodsite"
               mkdir -p "$prodsite"
               cp /etc/lighttpd/dev.conf "$prodsite/" ;;
  esac
  shift
done

$test || sudo true

if ! $test && pgrep lighttpd &>/dev/null; then
  echo 'stopping services...'
  sudo /etc/rc.d/lighttpd stop || errorout 'failed'
fi

cd "$devsite" || errorout 'failed to change directory'

if ! $test && $wipe; then
  if prompt "this will WIPE $prodsite/*, are you sure"; then
    echo 'wiping destination...'
    sudo find "$prodsite" -mindepth 1 -maxdepth 1 ! -name 'xmonad' -exec rm -rf {} \; || errorout 'failed to wipe destination.'
  fi
fi

echo 'updating template files...'
mv_file hamlet
mv_file cassius
mv_file pandoc
mv_file favicon.ico

if ! $post; then
  echo 'updating static files...'
  mv_file static
fi

compile_site

if $test; then
  cd "$prodsite"
  echo 'starting test server...'
  lighttpd -D -f dev.conf
else
  echo 'fixing permissions...'
  sudo chown -R http:http "$prodsite"
  sudo chown -R patrick:patrick "$prodsite/static"
  sudo chown -R patrick:patrick "$prodsite/xmonad"

  echo 'starting production services...'
  sudo /etc/rc.d/lighttpd start || errorout 'failed'
fi

echo 'done.'
