#!/bin/bash
#
# pbrisbin 2010
#
# don't run this as root as we rely on user-specific ENV vars and
# haskell modules; sudo is used for the parts that require it.
#
###

errorout() { echo "error: $*" >&2; exit 1; }
message()  { echo 'usage: deploy [ --force | --test | --help ]'; exit 1; }

cp_file() {
  local file="$1" dest="$2" _cp

  # need sudo to write to /srv/http
  $test && _cp='cp -r' || _cp='sudo cp -r'

  if [[ -e "$file" ]]; then
    $_cp "$file" "$dest/" || errorout "$file: failed to copy"
  else
    echo "omitting $file; does not exist" >&2
  fi
}

compile_app() {
  local dest="$1"

  # force ghc to recompile everything
  $force && find ./ -type f -name '*.hs' -exec touch {} \;

  $test || sed -i 's/^-- \(#define PRODUCTION\)$/\1/g' Settings.hs
  ghc --make -o app.cgi fastcgi.hs || errorout 'failed'
  $test || sed -i 's/^\(#define PRODUCTION\)$/-- \1/g' Settings.hs

}

test_deploy() {
  echo 'creating/wiping test directory...'
  [[ -d "$testsite" ]] || mkdir -p "$testsite"
  rm -rf "$testsite"/*

  # pull files down from prod
  echo 'updating test files from prod...'
  cp_file "$prodsite/pandoc" "$testsite/"
  cp_file "$prodsite/xmonad" "$testsite/"
  cp_file "$prodsite/static" "$testsite/"
  cp_file "$prodsite/favicon.ico" "$testsite/"

  # push files up from dev
  echo 'updating test files from dev...'
  cp_file hamlet "$testsite/"
  cp_file cassius "$testsite/"

  # setup lighttpd for local instance
  cp /etc/lighttpd/dev.conf "$testsite/"

  # recompile
  echo 'recompiling the application...'
  compile_app
  cp_file app.cgi "$testsite"

  # start services
  cd "$testsite"
  echo 'starting test server...'
  lighttpd -D -f dev.conf
}

prod_deploy() {
  # get our pw upfront
  sudo true

  # stop services
  if pgrep lighttpd &>/dev/null; then
    echo 'stopping services...'
    sudo /etc/rc.d/lighttpd stop || errorout 'failed'
  fi

  # push up to prod
  echo 'updating prod files...'
  cp_file hamlet "$testsite"
  cp_file cassius "$testsite"

  # recompile
  echo 'recompiling the application...'
  compile_app
  cp_file app.cgi "$prodsite"

  adjust_permissions

  # start services
  echo 'starting production services...'
  sudo /etc/rc.d/lighttpd start || errorout 'failed'
}

adjust_permissions() {
  echo 'fixing permissions...'
  sudo chown root:http "$prodsite"
  sudo chown -R patrick:http "$prodsite"/*
  sudo chown http:http "$prodsite/app.cgi"
  sudo chown http:http "$prodsite/client_session_key.aes"
  sudo chown http:http "$prodsite/comments.db"
}

# constants
devsite="$HOME/Code/haskell/devsite"
testsite="$HOME/http-test"
prodsite='/srv/http'

# defaults
force=false
test=false

# getopts
while [[ -n "$1" ]]; do
  case "$1" in
    -f|--force) force=true ;;
    -t|--test)  test=true  ;;
    *)          message    ;;
  esac
  shift
done

# run
cd "$devsite" || errorout 'failed to change directory'

if $test; then
  test_deploy
else
  prod_deploy
fi

echo 'done.'
