#!/bin/bash
#
# pbrisbin 2011
#
# auto-tag yesod projects to mark deployments for easy rollbacks.
#
###

[[ -d ./.git ]] || { echo 'not a git repository' >&2; exit 1; }

prefix='deployment' # no spaces

read -r version < <(git tag | sort -rn | sed '/^'"$prefix"'-\([0-9]\+\)/!d;s//\1/g')

version=$(( ${version:-0} + 1 ))

git tag -a -m "auto-tagged $prefix-$version" $prefix-$version

echo "tagged, $prefix-$version"
