#!/bin/bash
#
# pbrisbin 2010
#
# display an arbitrary message via dzen, good for notifications
#
###

# handle the event via dzen. this just throws $* into the dzen, so do
# any text formatting before passing into this function
handle_dzen() {
  local message="$*"

  # dzen settings
  local pipe='/tmp/android-receiver.fifo'
  local delay=4
  local x_offset=0
  local y_offset=0
  local height=17
  local font='Verdana-8'
  local foreground='#ffffba'
  local background='#303030'

  if [[ ! -e "$pipe" ]]; then
    mkfifo "$pipe"
    (dzen2 -ta l -h $height -x $x_offset -y $y_offset -fn "$font" -bg $background -fg $foreground < "$pipe"; rm -f "$pipe") &
  fi

  (echo "$message"; sleep $delay) >> "$pipe"
}

handle_dzen "$*"
