#!/bin/bash
#
# pbrisbin 2010
#
###

message() { echo 'usage: file2link <file>'; exit 1; }

[[ ! -e "$1" ]] && message

srv_lnk='http://pbrisbin.com'
srv_dir='/srv/http'

file="$(readlink -f "$1")"
link="${file/$srv_dir/$srv_lnk}"

echo -n $link | xclip &>/dev/null
echo $link
