#!/bin/bash -e

code="$HOME/Code/haskell"

if [[ "$1" =~ -u|--update ]]; then
  for repo in hamlet persistent wai yesod; do
    echo "updating $repo..."
    (
      cd "$code/$repo"
      git pull origin master
      git submodule update --init
      ./scripts/install --clean
    )
  done
fi

while read -r pkg; do
  echo "unregistering $pkg..."
  ghc-pkg unregister $pkg
done < <(ghc-pkg check |& grep '^[a-z]*-')
