#!/bin/bash
#
# pbrisbin 2012
#
###
broken_pkgs() {
  /usr/bin/ghc-pkg $* check \
    |& sed '/^There are problems in package \([^:]*\):$/!d; s//\1/'
}

case "$1" in
  clean)
    shift

    # this may need to be run multiple times to take care of cascading
    # borken packages.
    for pkg in $(broken_pkgs $*); do
      echo "attempting to unregister $pkg..."
      /usr/bin/ghc-pkg $* unregister $pkg
    done
    ;;

  reset)
    read -p 'Are you sure? ' ans

    if [[ "$ans" == 'yes' ]]; then
      rm -rfv "$HOME/.cabal/packages"/*/*
      rm -rfv "$HOME/.cabal/bin"/*
      rm -rfv "$HOME/.ghc"
    fi
    ;;

  # forward all else
  *) /usr/bin/ghc-pkg $* ;;
esac
