#!/bin/bash
#
# pbrisbin 2012
#
###
broken_pkgs() {
  /usr/bin/ghc-pkg "$@" check \
    |& sed '/^There are problems in package \([^:]*\):$/!d; s//\1/'
}

case "$1" in
  clean)
    shift

    # this may need to be run multiple times to take care of cascading
    # broken packages.
    for pkg in $(broken_pkgs "$@"); do
      echo "attempting to unregister $pkg..."
      /usr/bin/ghc-pkg "$@" unregister $pkg
    done
    ;;

  reset)
    read -p 'Are you sure? ' ans

    if [[ "$ans" == 'yes' ]]; then
      rm -rfv "$HOME/.cabal/packages"/*/*
      rm -rfv "$HOME/.cabal/bin"/*
      rm -rfv "$HOME/.ghc"
    else
      exit 1
    fi
    ;;

  reinstall)
    shift

    $0 reset     || exit $?
    cabal update || exit $?

    cabal install "$@" \
      ghc-mod \
      hoogle \
      xmonad \
      xmonad-contrib \
      yeganesh \
      pandoc \
      gravatar \
      friendly-time \
      sphinx \
      hjsmin \
      keter \
      persistent \
      persistent-postgresql \
      yesod \
      yesod-auth \
      yesod-form \
      yesod-newsfeed \
      yesod-persistent \
      yesod-static
    ;;

  # forward all else
  *) /usr/bin/ghc-pkg "$@" ;;
esac
