#!/bin/bash
#
# custom git commands/extensions. anything that isn't recognized should
# be a direct pass-through to normal git
#
###

original_args=( "$@" )

case "$1" in
  submodule)
    shift

    case "$1" in
      rm)
        if [[ "$1" == '-f' ]]; then
          shift; rm_files=true
        else
          rm_files=false
        fi

        shift; submodule="${1}"

        if [[ -n "$submodule" ]]; then
          # strip trailing slash(es) when present
          if [[ "$submodule" =~ ^(.*[^/])/*$ ]]; then
            submodule="${BASH_REMATCH[1]}"
          fi

          echo "removing submodule registration..."
          git config -f .git/config --remove-section submodule.${submodule}
          git config -f .gitmodules --remove-section submodule.${submodule}

          echo "removing committed files from tree..."
          git rm --cached "$submodule"

          if $rm_files; then
            echo "removing files..."
            rm -fr "$submodule/"
          fi

          exit $?
        fi

        ;;
    esac

    ;;
esac

# if the case statement doesn't exit, pass-through
/usr/bin/git "${original_args[@]}"
