#!/bin/bash
#
# pbrisbin 2010
#
# http://pbrisbin.com/bin/infinite
#
# create a screenshot of the forum sshot thread that contains a
# screenshot of the forum sshot thread that contains a screenshot
# of the forum sshot thread that contains a...
#
# requires your own server, scrot, and uzbl
#
#   1. determine screenshot filename
#   2. make post with -thumb url/img tags
#   3. open page in uzbl
#   4. determine uzbl socket
#   5. adjust constants in script
#   6. run script
#   7. hit Ctrl-C when you can't see any more layers
#   8. ???
#   9. profit
#
###

refresh_uzbl() {
  local socket="$1"

  echo reload | socat - unix-connect:$socket &>/dev/null
}

take_screenshot() {
  local shot="$1"

  # automatically creates -thumb version
  scrot -t 20 "$shot"
}

# adjust these before starting
shot='/srv/http/screenshots/desktop_loop.png' # location to keep the fullsize shot
socket='/tmp/uzbl_socket_20971523'            # socket of uzbl instance showing thread

# repeat
while true; do

  # take a shot and wait a second
  take_screenshot "$shot"
  sleep 1

  # refresh the window to see the new shot and wait 3 seconds
  refresh_uzbl "$socket"
  sleep 3

done

# don't leave me running...
