#!/bin/bash
#
# pbrisbin 2012
#
###
(( $# )) || { echo 'usage: iso [ file, ... ]' >&2; exit 1 }

tmp=/tmp/iso; mkdir -p "$tmp"

for file; do
  ln -s "$(readlink -f "$file")" "$tmp"
done

mkisofs -o ./files.iso -f -r -J -l -allow-leading-dots "$tmp"
