#!/bin/bash
#
# pbrisbin 2010
#
# http://pbrisbin.com/bin/launcher
#
# heavily based on ghost's dmlauncher:
#
# http://ghost1227.com/tech/software-scripts/a-not-so-simple-dmenu-wrapper/
#
###

message() { echo 'usage: launcher [ -a <executable> ... ] | [ -d <launcher> ... ]'; exit 1; }

errorout() { echo "error: $*"; exit 1; }

addlauncher() {
  local app

  for app in "$@"; do
    # not in our path
    which $app &>/dev/null || continue

    # already added
    [[ -L "$cache/$app" ]] &&  continue

    # add it
    ln -s $(which "$app") "$cache/$app" || errorout "$app: error adding launcher"
  done
}

dellauncher() {
  local app

  for app in "$@"; do
    # does it exist
    [[ -L "$cache/$app" ]] || continue

    # remove it
    rm -f "$cache/$app" || errorout "$app: error removing launcher"
  done
}

dmlrun() { 
  local exe

  exe="$((ls $cache; echo -e "add\ndel") | $DMENU)"
  
  if [[ -n "$exe" ]]; then
    case "$exe" in
      add\ *) $0 ${exe/add/-a} & ;;
      del\ *) $0 ${exe/del/-d} & ;;
      *)      exec $exe          ;;
    esac
  fi
}

parse_options() {
  # get a dmenu executable
  [[ -f "$HOME/.dmenurc" ]] && . "$HOME/.dmenurc" || DMENU='dmenu -i'

  # make cache
  [[ -d "$cache" ]] || mkdir -p "$cache"

  # getopts
  case "$1" in
    -h|--help) message                 ;;
    -a|--add)  shift; addlauncher "$@" ;;
    -d|--del)  shift; dellauncher "$@" ;;
    *)         dmlrun                  ;;
  esac
}

cache="$XDG_CACHE_HOME/launcher"

parse_options "$@"
