#!/bin/bash
#
# leave - pbrisbin 2011
#
# a simple shut-down dialog implemented via dmenu
# 
# note: requires NOPASWD entries for the commands involved (when not
# using --no-sudo).
#
# todo:
#       remove duplicate code re: --no-sudo
#       verify bash version supports assoc arrays
#
###

errorout() { echo "error: $*"                 ; exit 1; }
message()  { echo 'usage: leave [ --no-sudo ]'; exit 1; }

have() { which $1 &>/dev/null }

[[ "$1" =~ -h|--help ]] && message

declare -A choices

choices[logout]='pkill X'

if [[ "$1" == '--no-sudo' ]]; then
  choices[shutdown]='shutdown -h now'
  choices[reboot]='shutdown -r now'

  if have pm-suspend; then
    choices[suspend]='pm-suspend'
  else
    choices[suspend]='echo -n mem >/sys/power/state'
  fi

  have pm-hibernate && choices[hibernate]='pm-hibernate'
else
  have sudo || errorout 'no sudo binary found'

  choices[shutdown]='sudo shutdown -h now'
  choices[reboot]='sudo shutdown -r now'

  if have pm-suspend; then
    choices[suspend]='sudo pm-suspend'
  else
    choices[suspend]='sudo /bin/sh -c "echo -n mem >/sys/power/state"'
  fi

  have pm-hibernate && choices[hibernate]='pm-hibernate'
fi

dmenu="dmenu ${DMENU_OPTS:--i}"

choice="$(printf "%s\n" "${!choices[@]}" | $dmenu)" 

if [[ -n "$choice"]]; then
  action="${choices[$choice]}"
  [[ -n "$action"]] && $action
fi
