#!/bin/bash
#
# print a random mitch headberg quote
#
# significantly abstracted for ease of reuse
#
###

# required constants:
WHO="Mitch Headberg"
file="$HOME/.mitch_quotes" # $file has blocks of text separated by...
mark='MARK'                # $mark on a line by itself

# abstracted code:
print_block() {
  local top=${marks[$1]}   # the line num of the passed mark
  local bot=${marks[$1+$2]} # the line num of the next mark
  local H=$((bot-1))       # the arg for head -n to print up until the next mark (exclusive)
  local T=$((bot-top-1))   # the arg for tail -n to print down from the passed mark (exclusive)

  # and you're left with the text in between...

  echo
  echo -n "  "; head -n $H $file | tail -n $T
  echo
  echo "                                   -- $WHO"
  echo
}

# construct an array of line numbers, one for each $mark in $file
marks=( $(grep -nx $mark $file | cut -d ':' -f 1) )

# print a quote based on a random $mark from the array
print_block $[ ( $RANDOM % ${#marks[@]} ) + 1 ] 1
