#!/bin/bash
#
# pbrisbin 2010
#
# accepts any number of files as arguments. create a symlink in a data
# directory, then create a torrent for the symlinked file which will
# automatically start in the running rtorrent session.
#
###

errorout() { echo "$*" >&2; exit 1; }

outdir="$HOME/.gbs-torrents"
outdata="$HOME/.gbs-content"

announce='http://tracker.publicbt.com'
port=80

[[ -d "$outdir"  ]] || mkdir -p "$outdir"
[[ -d "$outdata" ]] || mkdir -p "$outdata"

for arg in "$@"; do
  [[ -f "$arg" ]] && files+=( "$(readlink -f "$arg")" )
done

pushd "$outdata" &>/dev/null || exit 1

for file in "${files[@]}"; do

  torfile="${file##*/}"
  torrent="$outdir/${torfile%.*}.torrent"

  if [[ ! -e "$torfile" ]]; then
    ln -s "$file" . ||\
      errorout "$file -> $torfile: failed to link."
  fi

  if [[ ! -e "$torrent" ]]; then
    createtorrent --announce "$announce" --port $port "./$torfile" "$torrent" ||\
      errorout "./$torfile -> $torrent: failed to create."
  fi

done

popd &>/dev/null
