#!/bin/bash
#
# pbrisbin 2010
#
# interact with mpd via mpc through some dmenu's
#
###

message() { echo 'usage: mpdmenu'; exit 1; }

find_track() {
  local choice

  sleep 0.5 && choice="$(mpc --format '%position% %title% by %artist% on %album%' playlist | cut -c 1-90 | $dmenu | cut -d ' ' -f 1)"
  [[ -z "$choice" ]] && return 1

  mpc --no-status play $choice
}

add() {
  local type="$1" clear="$2" choice

  sleep 0.5 && choice="$(mpc list "$type" | $dmenu)"
  [[ -z "$choice" ]] && return 1

  $clear && mpc --no-status clear
  mpc search "$type" "$choice" | mpc --no-status add
  mpc --no-status play

  return 0
}

add_all() {
  mpc --no-status clear
  mpc ls | mpc --no-status add
  mpc --no-status play
}

add_playlist() {
  local choice

  sleep 0.5 && choice="$(mpc lsplaylists | $dmenu)"
  [[ -z "$choice" ]] && return 1

  mpc load "$choice"
}

dmenu="dmenu ${DMENU_OPTIONS:--i}"

declare -A choices

choices['play/pause']='--no-status toggle'
choices['previous']='mpc --no-status prev'
choices['next']='mpc --no-status next'
choices['stop']='mpc --no-status stop'
choices['random']='mpc --no-status random'
choices['repeat']='mpc --no-status repeat'
choices['find track']='find_track'
choices['add artist']='add artist false'
choices['add album']='add album false'
choices['add track']='add track false'
choices['clear/add artist']='add artist true'
choices['clear/add album']='add album true'
choices['clear/add track']='add title true'
choices['add all']='add_all'
choices['add playlist']='add_playlist'


choice="$(printf "%s\n" "${!choices[@]}" | $dmenu)"
[[ -z "$choice" ]] && exit 1

action="${choices[$choice]}"
[[ -n "$action" ]] && $action
