#!/usr/bin/env ruby

def main(argv)
  type = argv.first || 'artist'

  choice = `mpc list #{type} | dmenu ${DMENU_OPTIONS:--i}`.strip

  if choice && choice != ''
    `mpc --no-status stop`
    `mpc --no-status clear`
    `mpc --no-status findadd #{type} '#{choice}'`
    `mpc --no-status play`
  end

rescue => ex
  $stderr.puts "#{ex}"
  exit 1
end

main(ARGV)
