#!/bin/bash
#
# note: mpc undocumented --format field %position%
#
###

if [[ -f "$HOME/.dmenurc" ]]; then
  . "$HOME/.dmenurc"
else
  DMENU='dmenu -i'
fi

[[ "$*" = 'all' ]] && regex='.*' || regex="$*"

# dmenu with my choice of font has a 90 character limit
choice=$(mpc --format '%position% %title% by %artist% on %album%' playlist | grep -i "$regex" | cut -c 1-90 | $DMENU | awk '{print $1}')

[[ -n "$choice" ]] && mpc --no-status play $choice
