#!/bin/bash
#
# pbrisbin 2009
#
###

# what time is it?
now=( $(date +'%H %M') )

# split that
h=${now[0]}
m=${now[1]}

# midnight
[ "$h" = '00' ] && h='12'

# match hours to words
hours=('one' 'two' 'three' 'four' 'five' 'six' 'seven' 'eight' 'nine' 'ten' 'eleven' 'twelve')

# set up AM / PM
hours=( ${hours[@]} ${hours[@]} )

# match minutes to words
minutes=('five' 'ten' 'quarter' 'twenty' 'twenty five')

# set up the worded time
case $m in
         0[0-2]) time="${hours[h-1]} o'clock"             ;; # 00-02
         0[3-7]) time="${minutes[0]} after ${hours[h-1]}" ;; # 03-07
  0[8-9]|1[0-2]) time="${minutes[1]} after ${hours[h-1]}" ;; # 08-12
         1[3-7]) time="${minutes[2]} after ${hours[h-1]}" ;; # 13-17
  1[8-9]|2[0-2]) time="${minutes[3]} after ${hours[h-1]}" ;; # 18-22
         2[3-7]) time="${minutes[4]} after ${hours[h-1]}" ;; # 23-27
  2[8-9]|3[0-2]) time="half past ${hours[h-1]}"           ;; # 28-32
         3[3-7]) time="${minutes[4]} of ${hours[h]}"      ;; # 33-37
  3[8-9]|4[0-2]) time="${minutes[3]} of ${hours[h]}"      ;; # 38-42
         4[3-7]) time="${minutes[2]} of ${hours[h]}"      ;; # 43-47
  4[8-9]|5[0-2]) time="${minutes[1]} of ${hours[h]}"      ;; # 48-52
         5[3-7]) time="${minutes[0]} of ${hours[h]}"      ;; # 53-57
         5[8-9]) time="${hours[h]} o'clock"               ;; # 58-59
esac

# it's about damn $time!
echo "it's about $time"
