#!/bin/bash
#
# pbrisbin 2009, 2010
#
###

. /home/patrick/.bin/siteutils

message() { echo 'usage: newpage <page name> | [ -f <full path> ]'; exit 1; }

prompt() {
  read -p "$*? [Y/n] " a
  
  case "${a:-y}" in
    y|Y) return 0 ;;
    *)   return 1 ;;
  esac
}

write_page_template() {
  local page="$1"

  cat > $page << EOF
<?php require('scripts/pagetemplate.php'); pageHead(); ?>

<p class="hidden" id="rss_description"></p>

<p class="hidden" id="rss_pubDate">$(date -R)</p>

<h1 class="title">Title</h1>
<hr />



<?php pageFoot(); ?>
EOF

}

[[ -z "$1" ]] && message

if [[ "$1" = '-f' ]]; then
  [[ -n "$2" ]] && page="$2" || message
else
  name="$(basename "$1")"

  case "$name" in
    *.php)  page="$pages/$name"      ;;
    *.html) page="$pages/$name"      ;;
    *)      page="$pages/$name.html" ;;
  esac
fi

[[ -e "$page" ]] && errorout "page $page already exists"

echo "new: $page..."
sleep 1

write_page_template "$page" || errorout "could not write $page"

# set an md5 of the unmodified template
check_md5 set "$page"

# +11 puts me just after the title block
vim +10 "$page"

# check a new md5 to see if we've changed anything
if check_md5 get "$page"; then
  echo "aborting unmodified page $page..."
  rm "$page" || echo 'failed to remove file'
  exit 1
fi

# update rss feed
prompt 'update RSS' && updaterss
