#!/bin/bash -e
#
# pbrisbin 2012
#
###
(( $UID )) && { echo 'you must be root' >&2; exit 1; }

read -r -a files < <(find "${1:-/etc}" -name '*.pacnew' -print)

(( ${#files[@]} )) || exit 1

for file in "${files[@]}"; do
  current="${file/.pacnew/}"

  read -r -p "[*] $file found. process it? [Y/n] " ans

  if [[ "$ans" =~ ^($|y|Y) ]]; then
    ${DIFFTOOL:-vimdiff} "$current" "$file"

    rm -iv "$file" # -i gets us prompting for free
    [[ -f "$file" ]] && mv -iv "$file" "$current"
  fi
done
