#!/bin/bash
#
# pbrisbin 2011
#
# allows playing of any file or files through mpd without actually
# adding them to your collection.
#
# usage: playnow <file> ...
#
###

temp='temp'

# assumes well-formed value in /etc/mpd.conf
read mdir < <(awk -F '"' -v home="$HOME" '/^music_directory/ { gsub(/~/, home); print $2 }' /etc/mpd.conf)
read -r n < <(mpc playlist | wc -l)

# don't clear temp if files are in playlist now
mpc --format '%file%' playlist | grep -q "^$temp/" || \
  { [[ -d "$temp" ]] && rm -r "$temp"; mkdir -p "$temp"; }

for file; do ln -sf "$(readlink -f "$file")" "$mdir/$temp/"; done

# update, add, and play
( mpc -q --wait update "$temp" || exit 1
  mpc -q        add    "$temp" || exit 1
) && mpc -q play $((n++))
