#!/bin/bash
#
# pbrisbin 2011
#
# fix terrible filenames
#
###

message() { echo 'usage: renamer [ --fake ] <target> ...'; exit 1; }

fix() {
  tr -d '\n' | tr -d '\t' | tr -d \' | tr -d \" |\
    sed -r -e 's/.*/\L&/g' \
           -e 's/[ -]/_/g' \
           -e 's/_+/_/g'   \
           -e 's/^_|_$//g'
}

fix_sub() {
  local dir="${1%/*}" old="${1##*/}" new
  read -r new < <(fix <<< "$old")

  if [[ "$old" != "$new" ]]; then
    echo "$dir/$old --> $dir/$new"
    $fake || mv -i "$dir/$old" "$dir/$new"
  fi
}

fix_dir() {
  local dir

  while IFS='' read -d '' -r dir; do
    fix_sub "$dir"
  done < <(find "$1" -depth -print0)
}

[[ -z "$*" ]] && message

fake=false
[[ "$1" = '--fake' ]] && { fake=true; shift; }

for arg; do
  [[ -d "$arg" ]] && { fix_dir "$arg"; continue; }
  [[ -e "$arg" ]] && { fix_sub "$arg"; continue; }

  message
done
