#!/bin/bash
#
# pbrisbin 2009
#
# take a retardedly named file or directory and rename it sanely
#
# adjust translate() as needed
#
###

message() { echo 'usage: renamer (--fake) <target> ...'; exit 1; }

# could always use more shit here...
translate() {
  tr -d '\n' | tr -d '\t' | tr -d \' | tr -d \" |\
    sed -r -e 's/.*/\L&/g' \
           -e 's/[ -]/_/g' \
           -e 's/_+/_/g'   \
           -e 's/^_|_$//g'
}

rfile() {
  local dir old new

  dir="$(dirname "$1")"
  old="$(basename "$1")"
  new="$(echo $old | translate)"

  if [[ "$old" != "$new" ]]; then
    if $fake; then
      echo "$dir/$old --> $dir/$new"
    else
      mv -iv "$dir/$old" "$dir/$new"
    fi
  fi
}

rdir() {
  local dir

  while IFS='' read -d '' -r dir; do
    rfile "$dir"
  done < <(find "$1" -depth -print0)
}

[[ -z "$*" ]] && message

# allow a pretend run
if [[ "$1" = '--fake' ]]; then
  fake=true
  shift
else
  fake=false
fi

# do it to it
for arg in "$@"; do 
  if [[ -d "$arg" ]]; then
    rdir "$arg"
  elif [[ -e "$arg" ]]; then
    rfile "$arg"
  else
    message
  fi
done
