#!/bin/bash

logger() { echo "$(date +'[ %d %b %Y %H:%M ]') :: $*" | tee -a "$tmplog"; }

errorout() {
  ( if [[ -n "$tmplog" ]]; then
      logger "error: $*"
    else
      echo "error: $*"
    fi

  ) >&2

  exit 1
}

send_to_log() {
  while read -r; do
    logger "$REPLY"
  done
}

archive_log() { cat "$tmplog" >> "$log"; }

mail_log() { su -c "echo see attached | mutt -s \"Root Kit Check\" -a \"$tmplog\" -- pbrisbin@gmail.com" patrick; }

# must be root
[ $(id -u) -ne 0 ] && errorout 'you must be root'

# location of logs
tmplog='/tmp/rootkit.log'
log='/home/patrick/.logs/rootkitcheck.log'

logger ' --- starting new check --- '
/usr/bin/rkhunter --versioncheck --nocolors                   | send_to_log
/usr/bin/rkhunter --update --nocolors                         | send_to_log
/usr/bin/rkhunter --cronjob --nocolors --report-warnings-only | send_to_log

if grep -Fq 'Please check the the log file' "$tmplog"; then
  archive_log
  mail_log
fi

rm "$tmplog"
