#!/bin/bash
#
# pbrisbin 2010
#
# http://pbrisbin.com/bin/runscript
#
# pass a script file (or command) and an interval (seconds are expected
# but it's passed directly to sleep so 5m or whatever would work too)
# and the command will be run on that interval forever. the pid is
# reported so that you can kill it when you're done
#
# output from the looped script is not suppressed so be sure to redirect
# it if you want it to be quiet.
#
###

if [[ $# -ne 2 ]]; then
  echo 'usage: runscript <command> <interval>'
  exit 1
fi

script="$1"
seconds="$2"

( while true; do
    $script
    sleep $seconds
  done ) &

pid="$!"

echo "executing \`$script\` every $seconds seconds"
echo "process id: $pid"
