#!/bin/bash
#
# pbrisbin 2010
#
###

errorout() { echo "$*" >&2; exit 1; }
message()  { echo 'usage: share <file>'; exit 1; }

[[ ! -e "$1" ]] && message

share='/srv/http/static/fileshare'

src="$1"
dst="$share/$(basename "$src")"

if [[ -d "$src" ]]; then
  mode=755
  _cp='cp -r'
else
  mode=644
  _cp='cp'
fi

$_cp "$src" "$dst" || errorout 'failed to copy'
chmod $mode "$dst" || errorout 'failed to set permissions'

file2link "$dst"
