#!/bin/bash

errorout() { echo "error: $*" >&2; exit 1; }

[[ $(id -u) -ne 0 ]] && exit 1

dir="${1:-/mnt/backup/website}"

[[ ! -d "$dir" ]] && errorout 'invalid directory'

src='/srv/http/'
dst="$dir/backup-$(date +%m%d).tar.bz2"

# clear out some old ones
find "$dir" -name 'backup-*' -mtime +28 -delete

# make a new one
tar -cjpP --ignore-failed-read -f "$dst" "$src"
