#!/bin/bash
#
# pbrisbin 2011
#
###

errorout() { echo "error: $*" >&2; exit 1; }

message() { echo 'usage: snapshot [file] ...'; exit 1; }

get_last_version() { ls -1 -t "$directory" | grep -E "/?${1##*/}\.[0-9]*" | head -n 1; }

get_next_version() { echo "$directory/${1##*/}.$(date +%s)"; }

get_md5sum() { 
  if [[ ! -f "$1" ]]; then
    echo ''
    return 1
  fi

  md5sum "$1" | cut -d ' ' -f 1
}

do_snapshot() {
  local file="$1" last_version last_md5sum new_md5sum

  new_md5sum="$(get_md5sum "$file")"

  last_version="$directory/$(get_last_version "$file")"
  last_md5sum="$(get_md5sum "$last_version")"

  if [[ "$new_md5sum" == "$last_md5sum" ]]; then
    echo 'files match. doing nothing.'
    return 0
  fi

  cp -v "$file" "$(get_next_version "$file")"
}

directory="$HOME/.snapshots"

[[ -d "$directory" ]] || mkdir -p "$directory"

for arg in "$@"; do
  do_snapshot "$arg"
done
