#!/bin/bash
#
# pbrisbin 2012
#
###
if (( ! $# )); then
  # simple, stdin usage
  read -r link < <(curl -s -F 'sprunge=<-' http://sprunge.us)
else
  read -r url < <(curl -s -F 'sprunge=<-' http://sprunge.us < "$1")

  ext="${1##*.}"

  if [[ "$ext" == "$1" ]]; then
    link="$url" # there was no extension
  else
    link="$url?${1##*.}"
  fi
fi

[[ -n "$DISPLAY" ]] && echo -n "$link" | xclip
echo "$link"
