#!/bin/bash
#
# pbrisbin 2009, 2010
#
# a general scrot wrapper script
#
###

message() { echo 'usage: sshot [ -n <name> ] [ -f ] [ scrot options ]'; exit 1; }

shots_dir='/srv/http/static/screenshots'
name="desktop_$(date +%y%m%d%H%M)"
sopts=('-t' '10')
forum=false

# grab some options for us, pass anything
# else directly to scrot
while [ -n "$1" ]; do
  case $1 in
    -h|--help)  message          ;;
    -f|--forum) forum=true       ;;
    -n|--name)  shift; name="$1" ;;
    *)          sopts+=( "$1" )  ;; 
  esac
  shift
done

shot="$shots_dir/${name// /_}.png"
thumb="${shot/.png/-thumb.png}"
scrot ${sopts[@]} "$shot" || exit 1

if $forum; then
  # [url= ][img]...
  thumb="${shot/.png/-thumb.png}"
  output="[url=$(file2link "$shot")][img]$(file2link "$thumb")[/img][/url]"

  echo -n "$output" | xclip &>/dev/null
  echo "$output"
else
  # direct link
  file2link "$shot"
fi
