#!/bin/bash -ex

cd ~/.xmonad || exit 1

HsColour -css -anchor xmonad.hs > docs/src/xmonad.html

for file in lib/*.hs; do
  HsColour -css -anchor "$file" > docs/src/$(basename "$file" .hs).html
done

haddock --no-warnings --html --title="pbrisbin modules" --odir=docs lib/*.hs \
  --source-module="src/%{MODULE/.//}.html" \
  --source-entity="src/%{MODULE/.//}.html#%{NAME}"

public="$HOME/Site/docs/haskell/xmonad-config"

rm -r "$public"/*
cp -r ./docs/* "$public"/
