#!/bin/bash

cd ~/.xmonad || exit 1

# create colored html source for xmonad.hs
HsColour -css -anchor xmonad.hs > docs/src/xmonad.html

# create colored html source for lib
for file in lib/*.hs; do
  HsColour -css -anchor "$file" > docs/src/$(basename "$file" .hs).html
done

# update documentation
haddock --no-warnings --html --title="pbrisbin modules" --odir=docs lib/*.hs \
  --source-module="src/%{MODULE/.//}.html" \
  --source-entity="src/%{MODULE/.//}.html#%{NAME}"
