#!/bin/bash
#
# pbrisbin 2012
#
###
file="$1"

[[ -z "$file" ]] && { echo 'argument required' >&2; exit 1; }

if [[ $file =~ ^magnet: ]] && [[ "$file" =~ xt=urn:btih:([^&/]+) ]]; then
  echo "d10:magnet-uri${#file}:${file}e" > "~/Downloads/meta-${BASH_REMATCH[1]}.torrent"
  exit 0
fi

if [[ ! -f "$file" ]]; then
  $BROWSER "$file" &>/dev/null &
  exit 0
fi

if ! which xdg-mime &>/dev/null; then
  echo 'xdg-mime required' >&2
  exit 1
fi

IFS='/' read -r major minor < \
  <(xdg-mime query filetype "$file" 2>/dev/null | cut -d ';' -f 1)

case "$major/$minor" in
  application/pdf) zathura "$file"  ;;
  application/ogg) mplayer "$file"  ;;

  *)
    case "$major" in
      text)        urxvtc -e vim "$file" ;;
      image)       mirage "$file"        ;;
      audio|video) mplayer "$file"       ;;
      *)
        echo "$file: unmatched mimetype, $major/$minor" >&2
        exit 1
        ;;

    esac
    ;;

esac
