#!/bin/bash
#
# pbrisbin 2012
#
# put this at /usr/bin/xdg-open (or just ahead of it in $PATH) and
# chromium will open apps sanely without all that .desktop crap
#
###

file="$1"

[[ -z "$file" ]] && { echo 'argument required' >&2; exit 1; }

if [[ $file =~ ^magnet: ]] && [[ "$file" =~ xt=urn:btih:([^&/]+) ]]; then
  echo "d10:magnet-uri${#file}:${file}e" > "~/Downloads/meta-${BASH_REMATCH[1]}.torrent"
  exit 0
fi

if [[ ! -f "$file" ]]; then
  $BROWSER "$file" &>/dev/null &
  exit 0
fi

if ! which xdg-mime &>/dev/null; then
  echo 'xdg-mime required' >&2
  exit 1
fi

# read the major and minor mimetype
IFS='/' read -r major minor < <(xdg-mime query filetype "$file" 2>/dev/null | cut -d ';' -f 1)

# check for a specific case
case "$major/$minor" in
  text/html)       $BROWSER "$file" &>/dev/null & exit 0 ;;
  application/pdf) zathura "$file"  &>/dev/null & exit 0 ;;
  application/ogg) playnow "$file"  &>/dev/null & exit 0 ;;
  audio/x-wav)     mplayer "$file"  &>/dev/null & exit 0 ;;
esac

# check for just a major match
case "$major" in
  image) mirage "$file"        &>/dev/null & exit 0 ;;
  audio) playnow "$file"       &>/dev/null & exit 0 ;;
  text)  urxvtc -e vim "$file" &>/dev/null & exit 0 ;;
  video) mplayer "$file"       &>/dev/null & exit 0 ;;
esac

echo "$file: unmatched on mimetype" >&2
exit 1
