#!/bin/bash
#
# pbrisbin 2010
#
###

errorout() { echo "error: $*" >&2; exit 1; }
message()  { echo 'usage: share [ -r ] <file>'; exit 1; }

if [[ "$1" =~ -r|--remove ]]; then
  remove=true
  shift
else
  remove=false
fi

if [[ $# -gt 1 ]]; then
  # share a group of files by archiving them, and then calling this 
  # script again with the archive as a single argument.. trippy
  archive="shared_$(date +%s).tgz"
  tar cvpzf "$archive" "$@"
  $remove && $0 -r "$archive" || $0 "$archive"
else
  [[ ! -e "$1" ]] && message

  share="$HOME/Site/files"

  src="$1"
  dst="$share/$(basename "$src")"

  if [[ -d "$src" ]]; then
    mode=755
    _cp='cp -r'
    _rm='rm -r'
  else
    mode=644
    _cp='cp'
    _rm='rm'
  fi

  $_cp "$src" "$dst" || errorout 'failed to copy'
  chmod $mode "$dst" || errorout 'failed to set permissions'

  $remove && $_rm "$src"

  file2link "$dst"
fi
